*** Variables ***
${defect_id}        None
${project}          Jira Scrum (JS)
${not_a_project}    Jira Scrum (JeeS)
${syncContext}      {"iTBProject": "string","lastSync": "2026-02-03T13:05:17.441Z","statusAttribute": "string","statusSyncOption": "ITB","priorityAttribute": "string","prioritySyncOption": "ITB","classAttribute": "string","classSyncOption": "ITB","serverTime": "2026-02-03T13:05:17.441Z","udaSyncOptions": {"additionalProp1": "ITB","additionalProp2": "ITB","additionalProp3": "ITB"},"syncOption": "USE_SYNC_MASTER","importNewDefects": true}
